name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects
      - name: Zip reposiroty code #Generamos un fichero zip del repositorio
        run: zip -r repository_code.zip .
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
      - name: Upload code zip as artifact #Subimos el zip generado como un artefacto
        uses: actions/upload-artifact@v2
        with:
          name: repository_code
          path: repository_code.zip
